#!/usr/bin/env python3
"""Inline templates/lab-ui.css into every HTML file that carries the Lab UI markers.

Lab UI is the visual language every Lab tool's HTML shares (the site's
alidemirbas.com.tr/lab pages, the journey canvas, the copy canvas, the report).
Each output must stay one self-contained file that renders offline, so the kit
is inlined rather than linked; this script is the one way an inlined copy is
written, so no file ever carries a hand-edited or stale kit.

A file opts in by holding, inside its <style>, the exact marker pair
  /* lab-ui:begin */ ... /* lab-ui:end */
and everything between them is replaced with templates/lab-ui.css verbatim.

Usage:
  sync_lab_ui.py            rewrite every marked file in place
  sync_lab_ui.py --check    exit 1 and list each marked file whose copy differs
                            (scripts/validate.sh runs this)
Skipped: .git/ and .gemini/ (the extension is generated by build_gemini.py
from these same sources), and output/ (user runs, never committed).
Exit: 0 = in sync / written, 1 = --check found drift, 2 = no kit file.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KIT = ROOT / "templates" / "lab-ui.css"
BLOCK = re.compile(r"(/\* lab-ui:begin \*/)\n.*?(/\* lab-ui:end \*/)", re.S)
SKIP = {".git", ".gemini", "output", "node_modules"}


def marked_files():
    for path in sorted(ROOT.rglob("*.html")):
        if SKIP.intersection(path.relative_to(ROOT).parts):
            continue
        text = path.read_text(encoding="utf-8")
        if "/* lab-ui:begin */" in text:
            yield path, text


def main(argv):
    check = "--check" in argv
    if not KIT.is_file():
        print(f"missing {KIT.relative_to(ROOT)}")
        return 2
    kit = KIT.read_text(encoding="utf-8").rstrip("\n")
    stale = []
    for path, text in marked_files():
        synced, n = BLOCK.subn(lambda m: m.group(1) + "\n" + kit + "\n" + m.group(2), text)
        if n != 1:
            print(f"{path.relative_to(ROOT)}: expected one lab-ui block, found {n}")
            stale.append(path)
            continue
        if synced != text:
            stale.append(path)
            if not check:
                path.write_text(synced, encoding="utf-8")
                print(f"synced {path.relative_to(ROOT)}")
    if check and stale:
        for path in stale:
            print(f"stale Lab UI copy: {path.relative_to(ROOT)}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
